import { createApp } from "vue";
import { createPinia } from "pinia";
import i18n from "./language/i18n";
import App from "./App.vue";
import router from "./router";
import AOS from "aos";
import "aos/dist/aos.css";
import "@/assets/index.css";
import "maz-ui/css/main.css";
import MazPhoneNumberInput from "maz-ui/components/MazPhoneNumberInput";
const app = createApp(App);
app.AOS = new AOS.init({ once: true });
app.use(createPinia());
app.use(router);
app.use(i18n);
app.component("MazPhoneNumberInput", MazPhoneNumberInput);
app.mount("#app");
